Repository sufst/pcb, pull requests merged in 2023-02, with the labels that each got.

#30 feat(tsal): completed pcb schematic and layout
  tsal/fp-lib-table
  tsal/sym-lib-table
  tsal/tsal.kicad_pcb
  tsal/tsal.kicad_pro
  tsal/tsal.kicad_sch
Labels: feature

#31 release(tsal): v1.1.3
  release/tsal/Layout.pdf
  release/tsal/Schematic.pdf
  release/tsal/fabrication.zip
  release/tsal/ibom.html
  release/tsal/info
  tsal/tsal.kicad_pcb
Labels: feature

#32 feat(bspd): completed layout
  bspd/BSPD.kicad_pcb
  bspd/BSPD.kicad_pro
  bspd/BSPD.kicad_sch
  bspd/brake-plausibility.kicad_sch
  bspd/scs-check.kicad_sch
  tsal/fp-lib-table
Labels: feature

#33 release(bspd): v1.0.1
  bspd/BSPD.kicad_pcb
  release/bspd/Layout.pdf
  release/bspd/Schematic.pdf
  release/bspd/fabrication.zip
  release/bspd/ibom.html
  release/bspd/info
Labels: feature

#35 fix(tsal): increase number of LED connections
  common/step/Molex-MicroFit-430450812.stp
  tsal/tsal.kicad_pcb
  tsal/tsal.kicad_sch
Labels: bug

#36 release(tsal): v1.1.4
  release/tsal/Layout.pdf
  release/tsal/Schematic.pdf
  release/tsal/fabrication.zip
  release/tsal/ibom.html
  release/tsal/info
  tsal/tsal.kicad_pcb
Labels: feature

#37 feat(vcu): add 3D models for Molex receptacles
  common/step/Molex-MicroFit-436450200.stp
  common/step/Molex-MicroFit-436450400.stp
  vcu/vcu.kicad_pcb
  vcu/vcu.kicad_pro
Labels: feature

#38 feat(tsal): add 3D models for Molex receptacles
  common/step/Molex-MicroFit-430250800.stp
  tsal/tsal.kicad_pcb
Labels: feature

#39 fix(tsal): resize switched ground plane
  tsal/tsal.kicad_pcb
  tsal/tsal.kicad_sch
Labels: bug

#40 release: tsal v1.1.5
  release/tsal/Layout.pdf
  release/tsal/Schematic.pdf
  release/tsal/fabrication.zip
  release/tsal/ibom.html
  release/tsal/info
Labels: feature

#42 fix(bspd): corrected footprints
  bspd/BSPD.kicad_pcb
  bspd/BSPD.kicad_sch
  bspd/brake-plausibility.kicad_sch
  bspd/scs-check.kicad_sch
Labels: feature

#43 release(bspd): v1.0.2
  bspd/BSPD.kicad_pcb
  bspd/BSPD.kicad_sch
  bspd/brake-plausibility.kicad_sch
  bspd/scs-check.kicad_sch
  release/bspd/Layout.pdf
  release/bspd/Schematic.pdf
  release/bspd/fabrication.zip
  release/bspd/ibom.html
  release/bspd/info
Labels: feature

#51 docs(bspd): add some more explanatory comments
  bspd/BSPD.kicad_sch
  bspd/brake-plausibility.kicad_sch
Labels: documentation
