Repository sufst/pcb, pull requests merged in 2023-04, with the labels that each got.

#75 fix(latching): corrected latching behaviour
  latching/latching.cir
  latching/latching.kicad_pcb
  latching/latching.kicad_pro
  latching/latching.kicad_sch
Labels: bug, documentation, feature

#77 fix(vcu): improve safety of input stages
  vcu/input-shift.kicad_sch
  vcu/vcu.kicad_sch
Labels: bug, feature

#76 feat(latching): revised layout for fixed latching logic
  latching/latching.kicad_pcb
  latching/latching.kicad_pro
  latching/latching.kicad_sch
Labels: feature

#78 release(latching): v1.1.0
  latching/latching.kicad_pcb
  latching/latching.kicad_sch
  release/latching/Layout.pdf
  release/latching/Schematic.pdf
  release/latching/fabrication.zip
  release/latching/ibom.html
  release/latching/info
Labels: feature

#79 feat(hvs): add fusing and adjust resistor values
  hv-sense/hv_sense.kicad_pcb
  hv-sense/hv_sense.kicad_pro
  hv-sense/hv_sense.kicad_sch
  hv-sense/logic.kicad_sch
Labels: feature

#81 release(hvs): v1.1.0
  hv-sense/hv_sense.kicad_pcb
  hv-sense/hv_sense.kicad_pro
  release/hv-sense/Layout.pdf
  release/hv-sense/Schematic.pdf
  release/hv-sense/fabrication.zip
  release/hv-sense/ibom.html
  release/hv-sense/info
Labels: feature

#74 fix(bspd): improve layout and fix connection issues
  bspd/BSPD.kicad_pcb
  bspd/BSPD.kicad_pro
  bspd/BSPD.kicad_sch
  bspd/brake-plausibility.kicad_sch
  bspd/scs-check.kicad_sch
  common/sufst-lib.pretty/Pad_1x5mm.kicad_mod
Labels: bug, feature

#82 release(bspd): v1.1.0
  bspd/BSPD.kicad_pcb
  release/bspd/Layout.pdf
  release/bspd/Schematic.pdf
  release/bspd/fabrication.zip
  release/bspd/ibom.html
  release/bspd/info
Labels: feature

#83 feat(vcu): add I/O for dash and shutdown interfacing
  vcu/can-transceiver.kicad_sch
  vcu/input-shift.kicad_sch
  vcu/mcu.kicad_sch
  vcu/output-shift.kicad_sch
  vcu/vcu.kicad_pcb
  vcu/vcu.kicad_sch
Labels: feature

#84 release(vcu): v1.3.0
  release/vcu/Layout.pdf
  release/vcu/Schematic.pdf
  release/vcu/fabrication.zip
  release/vcu/ibom.html
  release/vcu/info
  vcu/vcu.kicad_pcb
  vcu/vcu.kicad_pro
Labels: feature

#85 release(latching): v1.1.1
  latching/latching.kicad_pcb
  latching/latching.kicad_sch
  release/latching/Layout.pdf
  release/latching/Schematic.pdf
  release/latching/fabrication.zip
  release/latching/ibom.html
  release/latching/info
Labels: feature

#86 feat(telemetry): add 7 segment display driver
  common/step/MAX6955.step
  common/step/MAX6958BAEE_T.step
  common/step/NEO-M9N.stp
  common/sufst-lib.kicad_sym
  common/sufst-lib.pretty/MAX6955.kicad_mod
  common/sufst-lib.pretty/SOP63P602X175-16N.kicad_mod
  telemetry/mcu.kicad_sch
  telemetry/sym-lib-table
  telemetry/telemetry.kicad_pcb
  telemetry/telemetry.kicad_pro
  telemetry/telemetry.kicad_sch
Labels: feature

#87 release(telemetry): v1.0.0
  release/telemetry/Layout.pdf
  release/telemetry/Schematic.pdf
  release/telemetry/fabrication.zip
  release/telemetry/ibom.html
  release/telemetry/info
  telemetry/telemetry.kicad_pcb
Labels: feature

#93 feat(ail): create AIL PCB
  README.md
  ail/ail.kicad_pcb
  ail/ail.kicad_pro
  ail/ail.kicad_sch
  ail/fp-lib-table
  ail/sym-lib-table
  common/molex_microfit-43650-0214.kicad_sym
  common/step/Molex-MicroFit-436500214.stp
  common/sufst-lib.pretty/Molex_Micro-Fit_3.0_43650-0214_1x02_P3.00mm_Horizontal.kicad_mod
Labels: feature

#96 feat(segment): add isolation between TS and LVS
  segment/segment.kicad_pcb
  segment/segment.kicad_pro
  segment/segment.kicad_sch
Labels: feature

#95 feat(ail): add copper pour to MOSFET drains
  ail/ail.kicad_pcb
  ail/ail.kicad_pro
  ail/ail.kicad_sch
  ail/sym-lib-table
Labels: feature

#97 feat(test): initial design for test rig
  common/step/ALPS-RK09K.step
  common/step/OS102011MS2QN1.step
  common/step/RD902F-40-00D.step
  common/step/SS14MDP2.stp
  common/step/Tactile-Button.step
  common/sufst-lib.pretty/SS14MDP2_NKK.kicad_mod
  common/sufst-lib.pretty/SW_OS102011MS2QN1.kicad_mod
  test-rig/fp-lib-table
  test-rig/sym-lib-table
  test-rig/test-rig.kicad_pcb
  test-rig/test-rig.kicad_pro
  test-rig/test-rig.kicad_sch
Labels: feature

#101 release(test): v1.0.0
  release/test-rig/Layout.pdf
  release/test-rig/Schematic.pdf
  release/test-rig/fabrication.zip
  release/test-rig/ibom.html
  release/test-rig/info
  test-rig/test-rig.kicad_pcb
  test-rig/test-rig.kicad_pro
Labels: chore

#102 release(segment): v1.1.0
  release/segment/Layout.pdf
  release/segment/Schematic.pdf
  release/segment/fabrication.zip
  release/segment/ibom.html
  release/segment/info
  segment/segment.kicad_pcb
Labels: chore

#103 feat(dash): world's worst dashboard PCB
  dash/dash.kicad_pcb
  dash/dash.kicad_pro
  dash/dash.kicad_sch
  dash/fp-lib-table
  dash/sym-lib-table
Labels: feature

#104 release(dash): v1.0.0
  dash/dash.kicad_pcb
  dash/dash.kicad_pro
  dash/dash.kicad_sch
  release/dash/Layout.pdf
  release/dash/Schematic.pdf
  release/dash/fabrication.zip
  release/dash/ibom.html
  release/dash/info
Labels: chore

#105 release(trc): v2.0.0
  release/trc/Layout.pdf
  release/trc/Schematic.pdf
  release/trc/fabrication.zip
  release/trc/ibom.html
  release/trc/info
  trc/trc.kicad_pcb
  trc/trc.kicad_pro
Labels: chore

#106 chore: update to KiCAD 7
  bspd/BSPD.kicad_pcb
  bspd/BSPD.kicad_pro
  bspd/BSPD.kicad_sch
  bspd/brake-plausibility.kicad_sch
  bspd/scs-check.kicad_sch
  discharge-relay-breakout/discharge-relay-breakout.kicad_pcb
  discharge-relay-breakout/discharge-relay-breakout.kicad_pro
  discharge-relay-breakout/discharge-relay-breakout.kicad_sch
  hv-sense/hv_sense.kicad_pcb
  hv-sense/hv_sense.kicad_pro
  hv-sense/hv_sense.kicad_sch
  hv-sense/logic.kicad_sch
  latching/latching.kicad_pcb
  latching/latching.kicad_pro
  latching/latching.kicad_sch
  telemetry/GPS.kicad_sch
  telemetry/can-transceiver.kicad_sch
  telemetry/input-shift.kicad_sch
  telemetry/mcu.kicad_sch
  telemetry/telemetry.kicad_pcb
  telemetry/telemetry.kicad_pro
  telemetry/telemetry.kicad_sch
  telemetry/xbee.kicad_sch
  tsal/tsal.kicad_pcb
  tsal/tsal.kicad_pro
  tsal/tsal.kicad_sch
  vcu/can-transceiver.kicad_sch
  vcu/input-shift.kicad_sch
  vcu/mcu.kicad_sch
  vcu/output-shift.kicad_sch
  vcu/vcu.kicad_pcb
  vcu/vcu.kicad_pro
  vcu/vcu.kicad_sch
Labels: chore

#98 feat(loom): initial loom design
  loom/Accumulator.kicad_sch
  loom/Dash Box.kicad_sch
  loom/Ground Box.kicad_sch
  loom/Inverter.kicad_sch
  loom/Junction Box.kicad_sch
  loom/Loom.kicad_pcb
  loom/Loom.kicad_pro
  loom/Loom.kicad_sch
  loom/Motor-Resolver.kicad_sch
  loom/PDM.kicad_sch
  loom/Pedal Box.kicad_sch
  loom/TSAL.kicad_sch
  loom/sym-lib-table
Labels: feature

#107 feat(discharge): redesigned discharge + chores
  Discharge/Discharge.kicad_pcb
  Discharge/Discharge.kicad_pro
  Discharge/Discharge.kicad_sch
  Discharge/fp-lib-table
  Discharge/sym-lib-table
  common/sufst-lib.pretty/0.5S7B_1212S3UP.kicad_mod
  discharge-relay-breakout/discharge-relay-breakout.kicad_pcb
  discharge-relay-breakout/discharge-relay-breakout.kicad_sch
Labels: feature
